#!/bin/bash

if [[ "$#" -lt 1 ]]; then 
    echo "Range date is mandatory, e.g: \`20240527_20240602\` which whould be a directory inside the draft directory";
    exit 1;
fi

date="$1"
args="$2"

if test -d ./target/release; then
    ./target/release/generate -d "./draft/$date" -o "./release/$date" $args
elif test -d ./target/debug; then
    ./target/debug/generate -d "./draft/$date" -o "./release/$date" $args
else
    cargo run --release -- -d "./draft/$date" -o "./release/$date" $args
fi
